tenants:
  - tenant: "sandbox"
    rootDomain: "sandbox.example.com"
    ssoEnabled: true
    ttlAbsolute: "PT8H"
    ttlIdle: "PT30M"
    eligibleClients:
      - "verifier-client"

  - tenant: "sandboxDos"
    rootDomain: ""
    ssoEnabled: true
    eligibleClients: []

  - tenant: "sandboxTres"
    rootDomain: ""
    ssoEnabled: false
    eligibleClients: []